### ISSUE TITLE
model=16k

### ISSUE THREAD

**Issue by DanMerry** [sony/silentcipher#2]
![image](https://github.com/user-attachments/assets/0a37f34c-b0c8-45ab-bfac-8004988ecb45)
model=44.1k it works.

**Comment by mayank-git-hub-sony** [comment]
Hello DanMerry, thank you for raising this issue. The message for the 16khz model must be a length of 32 bits, so 4 8-bit digits should work. Instead of passing [123, 234, 111, 222, 11] to the model, you can pass [123, 234, 111, 222].

I will soon incorporate the changes in the demo file and add the corresponding documentation.

**Comment by GeWanying** [comment]
Hi, 

Thanks for sharing the code. I followed your suggestion on passing 4 8-bit digits but it still doesn't work. First is the `len(message_lst[i])` doesn't match the `message_len` defined in the hparams.yaml file. Then after manually matching them (set `message_len` to 17 instead of 16), I got the following error. Could you help to solve this issue? 
<img width="565" alt="Screenshot 2024-11-06 at 17 15 16" src="https://github.com/user-attachments/assets/4751b996-1160-4850-9525-2d708853ca20">
Many thanks in advance.

Wanying Ge
